### ISSUE TITLE
Example with @tanstack/react-query

### ISSUE THREAD

**Issue by bryanjtc** [simonboisset/trpc-remix-call#4]
Can you add an example with @tanstack/react-query?
Include useQuery and useMutation hooks

**Comment by simonboisset** [comment]
Hi !

Yes sure. I can work on it. Which specific use case would you like to see in the example? This will help me provide the most relevant code for your needs.

**Comment by bryanjtc** [comment]
Use this as the use case. The example is based on react router, but it can be repurposed for remix and trpc.

https://tanstack.com/query/latest/docs/framework/react/examples/react-router

**Comment by simonboisset** [comment]
I added more trpc calls examples here #5
